sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
before_install:
  - gem install bundler
  - bundle --version
matrix:
  exclude:
    - rvm: 2.2.5
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_50.gemfile
notifications:
  email: false
